In [1]:
import numpy as np


In [24]:
#basics 
#initializing an array
#one dimentional array
a = np.array([1,2,3], dtype = 'int32')
print(a)

[1 2 3]


In [15]:
#2dimentional array
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [16]:
#geting the dimentions 
a.ndim

1

In [17]:
#get shape
b.shape

(2, 3)

In [25]:
#get type
a.dtype

dtype('int32')

In [26]:
a.itemsize

4

In [27]:
#get total size
a.nbytes

12

In [29]:
#accessing /changing specific elements 
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [32]:
#get specific element using [r,c]

a[0,3]

4

In [36]:
#get specific row 
a[1, :]      # the : gives the whole row or column 

array([ 8,  9, 10, 11, 12, 13, 14])

In [38]:
#get column
a[:, 1]

array([2, 9])

In [39]:
#startindex:endindex:stepsize to get a range 

a[0,1: 6:2]

array([2, 4, 6])

In [41]:
#replacing numbers 
a[1,5] = 15
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 15 14]]


In [42]:
#initializing different types of arrays 

In [47]:
#all zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
#all ones matrix
np.ones((3,4),)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
#any other number
np.full((2,2), 34)

array([[34, 34],
       [34, 34]])

In [55]:
#any number alternatively 
np.full_like(a, 3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [59]:
#initializing random decimal numbers
np.random.rand(4,2)

array([[0.84189863, 0.96748178],
       [0.16187121, 0.19581747],
       [0.76860835, 0.89595783],
       [0.47889361, 0.69508478]])

In [61]:
#initializing random decimal numbers
np.random.sample(a.shape)

array([[0.64099819, 0.72155535, 0.3554273 , 0.88146371, 0.79577248,
        0.24761824, 0.24379176],
       [0.20159387, 0.48617914, 0.288603  , 0.65413505, 0.7718256 ,
        0.70947241, 0.87087847]])

In [65]:
#initializing random interger numbers
np.random.randint(5, size=(3,3))

array([[4, 2, 0],
       [3, 0, 1],
       [1, 4, 0]])

In [67]:
#identity matrix 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
#reapeating an array
arr = np.array([1,2,3,])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [80]:
arr = np.array([[1,2,3,]])
r1 = np.repeat(arr,3, axis =0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [90]:
w = np.ones((5,5))
print(w)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

w[1:-1,1:-1] = z
print(w)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [104]:
a = np.array([1,2,3])
b[0]= 100
print(b)
print(a)

[100   2   3]
[1 2 3]


In [100]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 2
print(a)

[1 2 3]


In [106]:
###maths

In [114]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [108]:
#addition
a+2

array([3, 4, 5, 6])

In [109]:
#subtraction
a-2

array([-1,  0,  1,  2])

In [110]:
#multiplication
a*2

array([2, 4, 6, 8])

In [111]:
#division
a/2

array([0.5, 1. , 1.5, 2. ])

In [115]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [116]:
a ** 2

array([ 1,  4,  9, 16])

In [117]:
#take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [118]:
#######linear algebra

In [120]:
a = np.ones((1,2,3))
print(a)

b =np.full((3,2), 2)
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]]
[[2 2]
 [2 2]
 [2 2]]


In [121]:
#matric multiply

np.matmul(a,b)

array([[[6., 6.],
        [6., 6.]]])

In [123]:
#finding determinant

c = np.identity(3)
np.linalg.det(c)

1.0

In [125]:
######statistics

In [127]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
np.min(stats)

1

In [132]:
np.max(stats)

6

In [133]:
###reorganizing arrqays 

In [135]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [138]:
##vertical stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack((v1,v2,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [143]:
#horizontal stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
####miscellaneous

In [ ]:
#loading data from file
filedata = np.genfromtxt('filename', delimeter='how the data is separated')
filedata = filedata.astype('int32')      #to change the data to intergers 


##bolean masking and advance indexing

In [ ]:
filedata[filedata > 50]   # numbers in the data greater than 50
np.any(filedata > 50, axis = 0)   # if any of the columns have values greater than 50 
np.all(filedata > 50, axis = 0)   #gives true the columns where all values are grater thatn 50 

((filedata > 50) & (filedata < 100))  #gives true the values that are greater than 50 and less than 100
(~((filedata > 50) & (filedata < 100))) #give the opposite of the above 